Vidly/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Customer
    {
        public byte Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public bool  IsSubscribedToNewsletter { get; set; }

        public MembershipType MembershipType { get; set; }

        [Display(Name = "Membership Type")]
        public byte MembershipTypeId { get; set; }

        [Display(Name = "Date of Birth")]
        public DateTime? Birthdate { get; set; }
    }
}

Vidly/Controllers/CustomersController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class CustomersController : Controller
    {
        //connect to database=_context or Db
        private ApplicationDbContext _context;

        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult New()
        {
            var membershipTypes = _context.MembershipTypes.ToList();
            var viewModel = new NewCustomerViewModel
            {
                MembersipTypes = membershipTypes
            };
            return View(viewModel);
        }

        // GET: Customers
        public ViewResult Index()
        {
            //var customers = GetCustomers.Tolist();
            var customers = _context.Customers.Include(c => c.MembershipType).ToList();

            return View(customers);
        }

        public ActionResult Details(int id)
        {
           // var customer = GetCustomers().SingleOrDefault(c => c.Id == id);
            var customer = _context.Customers.Include(c => c.MembershipType).SingleOrDefault(c => c.Id == id);

            if (customer == null)
                return HttpNotFound();

            return View(customer);
        }
    }
}

Vidly/Views/Customers/Details.cshtml
@model Vidly.Models.Customer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name </h2>

<ul>
    <li>Membership Type: @Model.MembershipType.Name</li>
    @if (Model.Birthdate.HasValue)
    {
        <li>Birthdate: @Model.Birthdate.Value.ToShortDateString()</li>
    }
</ul>

Vidly/Views/Customers/Index.cshtml
@using Vidly.Controllers
@model IEnumerable<Vidly.Models.Customer>
@*
    Note: I've set the model for this view to IEnumerable<Customer>.
    This is a simple interface implemented by the list class. Since
    in this view we only want to iterate over this list, and we don't
    need any of the operations in the List class (eg Add, Remove, etc),
    it's better to use the IEnumerable interface, which allows use to
    iterate over the list. If in the future, we replace the List with a
    different data structure, as long as it is enumerable, our view code
    will remain unchanged.
*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customers (@Model.Count())</h2>
@if (!Model.Any())
{
    <p>We don't have any customers yet.</p>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Customer Name </th>
            <th>Membership Type </th>
            <th>Discount Rate </th>
        </tr>
        </thead>
        <tbody>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@Html.ActionLink(customer.Name, "Details", "Customers", new { id = customer.Id }, null)</td>
                <td>@customer.MembershipType.Name</td>
                <td>@customer.MembershipType.DiscountRate %</td>
            </tr>
        }
        </tbody>
    </table>
}

Vidly/Views/Customers/New.cshtml
@*@model Vidly.Models.Customer*@
@model Vidly.ViewModels.NewCustomerViewModel
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Customer</h2>


@*// generate and create a new customer input field with
    validation and constraints from Customer Model*@

@using (Html.BeginForm("Create", "Customers"))
{  <div class="form-group">
       @Html.LabelFor(m => m.Customer.Name) 
       @Html.TextBoxFor(m =>m.Customer.Name, new { @class = " form-control" })
   </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Customer.Birthdate) 
        @Html.TextBoxFor(m =>m.Customer.Birthdate, new { @class = " form-control" })
    </div>    

    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m =>m.Customer.IsSubscribedToNewsletter) Subscribed to Newsletter?
        </label>
    </div>
  
    <div class="form-group">
        @Html.LabelFor(m => m.Customer.MembershipTypeId) 
        @Html.DropDownListFor(m =>m.Customer.MembershipTypeId, new SelectList(Model.MembersipTypes, "Id", "Name"), "Select Membership Type", new { @class = " form-control" })
    </div> 
}